### ISSUE TITLE
Question:  Applying a local tx without broadcasting

### ISSUE THREAD

**Issue by andreasgriffin** [bitcoindevkit/bdk#1003]
Applying/unapplying a local tx to the utxo set would be useful. It would allow to build a tree of transactions that are not (or cannot) be broadcasted yet.   
Is something like that planned?

- The logic would need to consider, that a tx, might invalidate other local transactions.
- A new onchain transaction invalidates a local transaction

**Comment by LLFourn** [comment]
This can be done in the `1.0-alpha.*` releases and all the "invalidation" stuff should be handled for you in some (hopefully) sensible way so that two conflicting things cannot appear in the same UTXO set (and all descendants). Not sure how well it's tested or what the exact rules we apply are. I think in `1.0-alpha.1` it will choose the most recently "seen" tx as the one that is in the canonical mempool and will not allow anything conflicting with it.

**Comment by andreasgriffin** [comment]
Thanks for the answer! That's awesome!
