### ISSUE TITLE
OfflineWallet limitations/bugs

### ISSUE THREAD

**Issue by sgeisler** [bitcoindevkit/bdk#108]
I found two limitations/bugs in `Wallet<OfflineBlockchain, _>` implementation:

- [ ] `is_mine` doesn't work properly as the DB isn't populated properly. Proposed fixes:
  * Either make the method unavailable
  * or implement script bruteforcing to find out if a script is ours
- [ ] `sign` doesn't work. The descriptor recovery is broken (is needed because the DB isn't populated with UTXOs) because it recovers the generic descriptor (drops last child number) while the finalizer in rust-miniscript expects a concrete descriptor with the full derivation paths.
  * I already have a working fix that could break other things, I opened #109 to discuss it

**Comment by afilini** [comment]
I don't think we can do much about `is_mine`, because that's not just related to databases when running with an offline client, but more generally to any client that hasn't been synced yet.

Nonetheless, when `is_mine` isn't available, `sign` should try to reconstruct the descriptor by looking at the psbt itself and its `witness_utxo` and/or `non_witness_utxo`. I guess something is broken there, I'll look into it and checkout your fix too.

**Comment by afilini** [comment]
I think I've found it: this piece of code should return `path_excluding_wildcard`, instead it returns `path`. The code in this repo assumed that it was getting only the "prefix", not the full path.

https://github.com/MagicalBitcoin/rust-miniscript/blob/e430365e38db1b80be05cb1231780dddfcac5c37/src/descriptor/mod.rs#L162-L176
