### ISSUE TITLE
Add integration tests for electrum, esplora, bitcoind_rpc crates

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1094]
**Describe the enhancement**  

Basic blockchain integration tests need to be added to confirm scan and sync in different scenarios. 

**Use case**  

Example scan and sync test scenarios:

- single xkey or single key descriptors
- multisig xkey or single key descriptors
- multisig with mix of xkey and single key descriptors
- chain reorg
- synchronous or async

**Additional context**

Originally suggested by @danielabrozzoni  on discord: https://discord.com/channels/753336465005608961/753367451319926827/1144280548802572319

**Comment by notmandatory** [comment]
To reduce duplicate code this should be done after bitcoindevkit/bdk#2098, with similar consolidated `TestEnv` for `electrum` and `bitcoind_rpc` crates.

**Comment by danielabrozzoni** [comment]
One of my biggest doubt for this is how to test examples. Running `cargo test` automatically checks that examples build, but we also need to test that they work correctly (otherwise we might have problems such as bitcoindevkit/bdk#1125 or bitcoindevkit/bdk#1151).

We might decide to duplicate the examples code into our tests, but then we need to make sure that the two stay up to date one with the other.

**Comment by nondiremanuel** [comment]
According to our previous discussion, for the moment I assign the beta release to both this and the bitcoindevkit/bdk#2098 issue and then if we can make it in time for alpha.3 they can be included

**Comment by notmandatory** [comment]
Blockchain crates have good test coverage, see bitcoindevkit/bdk#906. We should open new issues for specific scenarios that need more testing.
