### ISSUE TITLE
Further improve unconfirmed tx conflict resolution

### ISSUE THREAD

**Issue by evanlinjin** [bitcoindevkit/bdk#1102]
**Describe the enhancement**  

At the end of ticket #1063's description, there is a **Further work** section which states:

> Our current structures do not handle unconfirmed conflicts properly when the conflicting transactions have the same `last_seen` timestamp (thanks to @rajarshimaitra for pointing this out).
>
> https://github.com/bitcoindevkit/bdk/blob/fe7bba1d9fcbfd9188fb036f7f2b488e62992a96/crates/chain/tests/test_indexed_tx_graph.rs#L692-L695
>
> I propose we deal with this as follows:
>
> When two unconfirmed txs conflict, but have the same last_seen, we can check the input's sequences (using RBF rules). Otherwise, we sort by feerate (if possible). We fallback to lexicographical sorting of txids.

**Comment by LLFourn** [comment]
@evanlinjin I don't understand how do we fall back to checking the input's nsequence?

I would not use RBF flagging since it isn't even being enforced anymore by lots of miners: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-August/021890.html

Check if one tx has a higher absolute fee and feerate and then choose that one. If they can't be distinguished using this rule then I would just report one arbitrarily. Reporting both transactions as conflicted sounds like it could be useful. I'm not sure how this would bubble up to `filter_chain_unspents`.

**Comment by evanlinjin** [comment]
@LLFourn I agree that we should just base it on fee/feerate only (so no `nsequence`).

The root of the problem would be in `get_chain_position`, which would bubble up to `filter_chain_unspents`, `list_chain_txs`, etc.
