### ISSUE TITLE
Fix clippy warnings for all optional features

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#126]
Warnings can be found with commands 

- `cargo clippy --features compact_filters --no-default-features`

Also need to fix:

- wallet/utils.rs#106, fix and remove `#[allow(dead_code)]`
- database/any.rs#325, fix and remove `#[allow(irrefutable_let_patterns)]`

After warnings are fixed enable clippy checks by default in `cont_integration.yml` for the `build-test` job:
   
- for `strategy.matrix.include` remove any with: 
   `clippy: false`
   
- and in the `clippy` step remove:
    `if: ${{ matrix.clippy == true }}`

**Comment by notmandatory** [comment]
One thing I forgot to mention in this issue is that we're currently using `stable` version of clippy, if you are using `nightly` you will get a lot more warnings. With `stable` we should have just one warning left to fix:  
```
$ cargo +nightly clippy --features "compact_filters" -- -D warnings
...
error: the `err @ _` pattern can be written as just `err`
   --> src/error.rs:196:13
    |
196 |             err @ _ => Error::CompactFilters(err),
    |             ^^^^^^^ help: try: `err`
    |
    = note: `-D clippy::redundant-pattern` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_pattern
```
Once this is fixed we can fix the CI to run clippy for all the features in our matrix.

**Comment by josediegorobles** [comment]
Hi, is this issue finish?

The fixes and changes in integration are made, as far as I can see.

When I run the cargo cargo clippy --features compact_filters --no-default-features

I get:

warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

error: failed to run custom build command for `librocksdb-sys v6.11.4`

Caused by:
  process didn't exit successfully: `/home/jdrobpar/projects/rust/bdk/target/debug/build/librocksdb-sys-e1eb642546a5ea2b/build-script-build` (exit code: 101)
  --- stdout
  cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
  cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\', \'libclang-*.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/jdrobpar/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.54.0/src/lib.rs:1959:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed


Are there any other good first issues? I'm an experienced developer but I recently introduced myself with Rust and Bitcoin and I want to contribute (and learn) with an interesting open source project like this.

**Comment by afilini** [comment]
I don't think this has anything to do with clippy specifically, I think it's just the fact that `librocksdb` (which is used in the compact filters implementation) requires `clang` to build. You can try installing `clang` from your distro and then it should work.

**Comment by josediegorobles** [comment]
Of course! It's all working now. Thanks.
If anyone can recommend some other issue for beginners...

**Comment by lvaccaro** [comment]
Hi @josediegorobles , I am a beginner too and I start [btctipserver](https://github.com/lvaccaro/btctipserver) project with contributions of bdk team. Feel free to add your thoughts and feelings. There is also a good first issue  https://github.com/lvaccaro/btctipserver/issues/25 . Sorry if this message looks OT.

**Comment by josediegorobles** [comment]
Hi, @lvaccaro, I found it interesting the project, I launch a PR for the problem, I will explore the project more.

**Comment by notmandatory** [comment]
Closing this since all issues have already been fixed.
