### ISSUE TITLE
feat: Get Wallet's Public/Private Keys (not the hash)

### ISSUE THREAD

**Issue by storopoli** [bitcoindevkit/bdk#1284]
**Describe the enhancement**  

Something like `wallet.pks_of_keychain[s]()`.

**Use case**  

Sometimes we want the underlying Public Key unhashed. This is what is being inserted in the witness block in P2WPKH for example.

**Comment by notmandatory** [comment]
Since a descriptor doesn't always map to a particular pub/sec key do you mean to get the script (or key if bare,pkh,wpkh)? We already have a way to get the descriptor from a wallet, does the [`Descriptor::explicit_script()`](https://docs.rs/miniscript/latest/miniscript/descriptor/enum.Descriptor.html#method.explicit_script) function give you what you're looking for?

**Comment by storopoli** [comment]
Humm I see. I could wrap get the descriptor for a specific spk and then call this.
Or even do a `.map` in an interator and collect a bunch of them.

Yes, this works. Thanks!
