### ISSUE TITLE
What is the purpose of the `chain_tip` argument to the `ChainOracle.is_block_in_chain()` method?

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/bdk#1302]
I'm looking into the `LocalChain` and `ChainOracle` types, and I have a question I can't quite answer from looking at the codebase: why is the `chain_tip` argument required on the `ChainOracle.is_block_in_chain()` method?

My current understanding of the use for the chain oracle is that it tells you whether an anchor is in your local chain (so that you can consider a transaction to be in the best chain as well, if it's anchored to that anchor). Under this assumption, why doesn't the oracle simply take a `BlockId` and tell you whether it's in its chain or not?

**Comment by LLFourn** [comment]
The chain tip determines which chain you're asking about. There are many valid Bitcoin blockchains each ending in different blocks. There is one longest one at this very moment which we call the canonical block chain but there are others, for example [this one](https://mempool.space/block/00000000000000000002c7de4016a0d09a47c19075cb73947e7f66e3461efd27). When you are querying the `ChainOracle` you have to tell it which chain you are asking about so it can give you a definite answer. It's just not possible to know whether the block is in the chain otherwise.

> My current understanding of the use for the chain oracle is that it tells you whether an anchor is in your local chain

A `LocalChain` is a chain oracle but it may not be the one you are using. For example, you may have a Bitcoin node running locally and you may just query it to find out which blocks are in the chain. You'd do this by implementing `ChainOracle` on some wrapper around a bitcoin rpc client.

Some confusion on this topic may come from the design of `LocalChain`. It can't answer for stale blocks so why have this API?
The main answer is that this API is not meant only for `LocalChain`. It would be good to replace `LocalChain` in the future with a monotone version (see bitcoindevkit/bdk_wallet#148). In this case `LocalChain` will remember stale blocks and allow you to query about them (it will never delete blocks).  But even for `LocalChain` as it is right now it's better to have it this way -- the caller should be explicit about which block it considers to be the tip when it is making queries so that you can make consistent queries even if the local chain were to change its tip in between queries.

**Comment by thunderbiscuit** [comment]
Thank you for the detailed response! Thinking of it as potentially a call on an rpc rather than the `LocalChain` made it clearer for me.
