### ISSUE TITLE
example: Fix wallet examples

### ISSUE THREAD

**Issue by ValuedMammal** [bitcoindevkit/bdk#1434]
These are some fixes that can be implemented for the `wallet_*` examples in the example-crates dir.

- [x] Print balances either in BTC or sats (but not both)
- [x] `wallet_esplora_async` appears to be printing the KeychainKind twice, and forgets to print spk0
- [x] Use [tempfile](https://docs.rs/tempfile/latest/tempfile/) instead of `std::env::tempdir`, as this should automatically clean up temporary files
- [x] Consider changing wallet examples to use signet and possibly a different server URL to fix rate limiting issues
- [x] Try to recycle the sats so that running an example doesn't result in a net loss of "funds"

**Comment by storopoli** [comment]
You can assign this to me.
I am eager to help.

**Comment by storopoli** [comment]
@ValuedMammal the problem with

>  - [ ] Consider moving these smaller examples to the bdk/examples folder

is that we cannot add them to the `wallet/examples` folder is due to the fact that `bdk_esplora` and `bdk_electrum` crates are not dependencies for `bdk_wallet`.
Hence we cannot add them to the cargo examples.

However we can circumvent this by adding both `bdk_electrum` and `bdk_esplora` to the `dev-depencies` of `bdk_wallet`.
Which I think is not worth it the extra overhead.

Source: https://users.rust-lang.org/t/cargo-example-only-dependencies/3215

**Comment by ValuedMammal** [comment]
> we cannot add them to the `wallet/examples` folder is due to the fact that `bdk_esplora` and `bdk_electrum` crates are not dependencies for `bdk_wallet`.

you're right, they will probably have to stay in example-crates
