### ISSUE TITLE
Move `CombinedChangeSet` back to `bdk_wallet::ChangeSet`

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1496]
Sub-task for #1103

**Comment by evanlinjin** [comment]
This is in-progress and I'm working on it!

**Comment by evanlinjin** [comment]
So just a quick update on this. Because this affects `bdk_sqlite` crate, I had to start changing that as well. This is why this PR is taking longer than expected. I've decided to follow @LLFourn's suggestion on implementing a sqlite trait on each changeset (still WIP).

I'll continue on this work on Monday. Clocking off for the weekend!
