### ISSUE TITLE
bdk_esplora: handle empty /blocks response

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1696]
"a rogue Esplora server can make an application crash by returning an empty list of blocks to a /blocks request, as latest_blocks is assumed to never be empty in fetch_block()"

**Comment by oleonardolima** [comment]
A new error variant was added to `rust-esplora-client`, that covers this scenario, as per https://github.com/bitcoindevkit/bdk/pull/1725#issuecomment-2518738172

However, I think we could have another issue with refactoring (both fetch_block and point of agreement logic) it posts 1.0 and using a defensive implementation instead of using the `.expect`, as ValuedMammal previous suggestions.

**Comment by notmandatory** [comment]
To resolve this issue we need to make a new `rust-esplora-client` 0.12.0 release and update `bdk_esplora` to use that dependency right? I propose this can wait until post 1.0.0.

**Comment by oleonardolima** [comment]
Rob's fix has been included as part of `0.11.0` release, so it's fixed by #1746.
