### ISSUE TITLE
PSBT missing PSBT_IN_NON_WITNESS_UTXO and PSBT_GLOBAL_XPUB fields - add support to add those in the repl CLI

### ISSUE THREAD

**Issue by benma** [bitcoindevkit/bdk#199]
Hi

Based on this report: https://github.com/benma/HWI/issues/2

It seems that the PSBT generated by this tool is missing those two fields:

For all transcations: **non_witness_utxo**, for each input, should contain the full prevtx, *even for segwit inputs*. This should be provided also for segwit inputs since the fee attack was discovered. See also: https://github.com/spesmilo/electrum/pull/6198

For multisig transactions:  **xpub**: some signers need to know the xpubs involved to be able to identify the multisig setup.

**Comment by afilini** [comment]
I think there should be some flags to do that in the library, one is called `force_non_witness_utxo` and I'm not sure about the other one but it could be `include_output_redeem_witness_script`. It was added to make multisig setups work on coldcards, so it might be the same.

I guess we should expose those to the CLI as well, there's no way right now to enable them from the `repl`..

**Comment by benma** [comment]
You could consider making these flags on by default, as it is a prerequisite for secure signing on offline signers.

Otherwise let's turn this issue into adding support for them in the CLI ;)

**Comment by benma** [comment]
@afilini thanks a lot for the commit. Any chance to also add the PSBT_GLOBAL_XPUB entries?

**Comment by afilini** [comment]
Yeah I've also added that. It doesn't show here but it's part of PR #200 

It's still a draft at the moment since I have to add tests and docs for the new stuff, but it should already be working!

**Comment by afilini** [comment]
I'm not sure about enabling those by default, we'll have to think about that. I definitely wouldn't do that right in the library, but maybe in the CLI it could make sense.. but again, if you make a tx and sign it with BDK or with Bitcoin Core for instance you don't actually need them, so I'm more inclined to making it opt-in rather than opt-out for the moment.

**Comment by benma** [comment]
Great. As long as it's possible to add them, it's a good step forward.

Default still might make sense as they are needed in the general case (e.g BitBox02, Trezor, Ledger need it to be able to safely sign, otherwise the input amounts cannot be verified). Too much info should not hurt too much, unless it is costly go get this extra info.

**Comment by afilini** [comment]
I'm mostly concerned about the size of PSBTs, especially for people that want to encode them in QR codes or in some cases copy/paste them. That's why I'd like to avoid making them larger by default

**Comment by afilini** [comment]
Just to check that I'm interpreting the BIP right: if my descriptor is

```wpkh(wpkh([2cbe2a6d/0'/1']tpubDBrgjcxBxnXyL575sHdkpKohWu5qHKoQ7TJXKNrYznh5fVEGBv89hA8ENW7A8MFVpFUSvgLqc4Nj1WZcpePX6rrxviVtPowvMuGF5rdT2Vi/2))```

then I should add the `PSBT_GLOBAL_XPUB` entry as follows, right?

key: `01 043587cf02e9378b87800000011061f793a9ead17f8972dacb485e226641b6ef8e8d8bcbe88a47aeb0ee3832d803d58a31091e99e7b0dec7b1c6515f3b538f9efb31fa6bbf7818bfafc9c85d79fb`
value: `2cbe2a6d 00000080 01000080 02000000` (spaces added just to make it more readable)

What isn't very clear to me is whether I should include the steps that have already been done on the xpub (`m/0'/1'`) or not. There are also cases where we might not know them, for instance if the user omits the "origin" part of the key. Should we give an error in that case?

**Comment by benma** [comment]
Is your account at `m/0'/1'` or at `m/0'/1'/2`?

I think it is most helpful if the the keypath in the xpub value in the PSBT points to the account-level. The BitBox02 can only sign a PSBT if this is the case, otherwise it cannot identify which of the xpubs belongs to it.

If you have an account at say `m/48'/0'/0'/2'`, with addresses at `m/48'/0'/0'/2'/<change>/<address>`, then the keypath in the xpub entry should be `m/48'/0'/0'/2'`, and the inputs/changes contain the full path up to the address.

So far I have only seen descriptors that contain the account-level keypath in the origin (inside `[...]`), with the address derivation keypath as a suffix.

I haven't checked if your binary representation is correct. Please let me know if I should do that too.

**Comment by benma** [comment]
> What isn't very clear to me is whether I should include the steps that have already been done on the xpub

Yes it should. The reason is that a signer needs to derive its own xpub based on that origin keypath to identify itself (because there could be fingerprint collisions).

I think erroring makes the most sense if the info is missing. Electrum has a different approach and basically just modifies the xpub and drops the keypath, which makes it technically a valid PSBT, but makes it impossible to identify a registered multisig account: https://github.com/spesmilo/electrum/issues/6780#issuecomment-733906282

**Comment by afilini** [comment]
Thanks for clarifying this, I think I'm doing it wrong now. I'm including the "full path", not only the "account level" path. To make a more realistic example with BIP48:

Given a descriptor like `wpkh([aabbccdd/48'/0'/0']xpub.../0/*)`, the current implementation would encode the `PSBT_GLOBAL_XPUB` with the full path like `m/48'/0'/0'/0/0`, `m/48'/0'/0'/0/1`, `m/48'/0'/0'/0/2`, etc, but since the key is the same (just `01 | xpub`) only the last entry would make it to the final PSBT. And also it would probably be wrong and I guess BitBox02 would refuse to sign.

Instead I should only encode the "origin path", and then the final derivation steps can be inferred by looking at the bip32 paths for each input that are always provided.

Since the option to include `PSBT_GLOBAL_XPUB` won't be enabled by default I think it makes sense to give an error if the origin is missing: as a user of this library you'll still be able to provide xpubs without origin and use pretty much anything the library has to offer, but if you try to enable the option to encode the xpubs in the PSBT you'll get an error that says that your keys need the origin. I guess the only case where that's not required is if the xpub has a depth of 0, in that case the "origin" key is that key itself, so we can just encode the fingerprint of that same xpub and an empty path.

As a side note, do you have a simulator/emulator for BitBox02 that I can try out to make sure my implementation works before merging it?

**Comment by benma** [comment]
You are correct, the BitBox02 would not be able to sign this, as it would try to derive the account xpub at the wrong path, and it would not match the actual xpub encoded in the PSBT. The keypath in the global xpub entry should be `m/48'/0'/0'` in your example, and the inputs and changes should have the full keypath.  

> As a side note, do you have a simulator/emulator for BitBox02 that I can try out to make sure my implementation works before merging it?

Unfortunately a simulator does not exist yet.
