### ISSUE TITLE
feature request: unconfirmed balances

### ISSUE THREAD

**Issue by domegabri** [bitcoindevkit/bdk#238]
At the moment `get_balance` returns the full wallet balance regardless of confirmations.

It would be nice to return unconfirmed balance as well or allow the caller to pass confirmation number.

**Comment by RCasatta** [comment]
in my opinion, latest `getbalances` from core use a more interesting distinction:
* `trusted` all confirmed and also unconfirmed generated by my wallet
* `untrusted_pending` unconfirmed received by other wallets

the rationale is that I can trust my own unconfirmed transactions

**Comment by LLFourn** [comment]
Just wanted to make a note that this is the algorithm I use for this in gun: https://github.com/LLFourn/gun/blob/ef3466d471bed8223b6af4f3e31d11fd5caf3f75/src/cmd/wallet.rs#L61-L67

The basic idea is that if a incoming UTXO is to an internal address then it's confirmed even if it's not confirmed in on chain because if it were to be dropped the coins would go back to wallet. This is something like what @RCasatta mentions above.

**Comment by danielabrozzoni** [comment]
> - trusted all confirmed and also unconfirmed generated by my wallet
> - untrusted_pending unconfirmed received by other wallets

Maybe we should also add an "immature" balance after I fix #413, as you can't spend immature coinbases anyways...

**Comment by rajarshimaitra** [comment]
I think something like this could work.. 
```
{
immature: All coinbase not matured yet
tursted pending: In wallet change utxo, but not confirmed yet.
untrusted pending: Other wallet received urtxo not confirmed yet.
available: All rest available balance
}
```

I did find few lib users confused by getting one single balance, devs expect their balances to be categorized in this way..

**Comment by danielabrozzoni** [comment]
Assigning to @wszdexdrf, so he can start contributing to bdk :)
Notice that this feature needs #614 merged first
