### ISSUE TITLE
Wallet export support

### ISSUE THREAD

**Issue by Fonta1n3** [bitcoindevkit/bdk#31]
Seeing as you guys are a descriptor based wallet it would be really cool if you could support this wallet export/import format: https://github.com/Fonta1n3/FullyNoded/blob/master/Docs/Wallets.md

It is quite simple and is made possible by directly relying on Bitcoin Core descriptors. The functionality is live on [Fully Noded](https://github.com/Fonta1n3/FullyNoded) and [Specter-Desktop](https://github.com/cryptoadvance/specter-desktop), hopefully more wallets will start to use this format as it offers an excellent way for users to backup, export and import wallets.

**Comment by afilini** [comment]
Sure, that's fairly easy to add. One question though: importing should be pretty easy for us, but should we also export descriptors that contains operators not (currently) supported by Core?

Because in your spec it's pretty clear that the descriptor should be a "Bitcoin Core" descriptor, and these are not :/

**Comment by Fonta1n3** [comment]
Do you have some docs that describe those?Would be happy to add support for them if I can.

**Comment by afilini** [comment]
I'm not sure it's that easy unfortunately, you would probably have to change quite a few things in Core.

This project uses [rust-miniscript](https://docs.rs/miniscript/1.0.0/miniscript/miniscript/decode/enum.Terminal.html) as its "descriptor engine", but I don't think they have documented anywhere the list of operators they support (the link here refers to the enum in their codebase that has every possible node in the AST). But it's pretty similar to the C++ version of miniscript, so you can have a look [here](http://bitcoin.sipa.be/miniscript/) and it should be more or less the same.

There are many operators that, afaik, are not in Core, like `older()`, `after()`, all the hash types, and even control flow operators like `and_*()` etc.

**Comment by Fonta1n3** [comment]
hmmm isn't miniscript a totally different thing? I did not know you were referring to miniscript when your docs say descriptors.

It looked like from your docs you do support Bitcoin Core descriptors, some inter wallet compatibility is better then none ;-) You could just add the export functionality for Bitcoin Core compatible descriptors which you do seem to support.

**Comment by afilini** [comment]
Well, yeah, the miniscript langauge is a totally different thing, but it can be compiled down to "descriptors" which is what I'm using in this project. Basically I'm using rust-miniscript to parse the descriptor, so I get for free support for all these other operators.

This is still not 100% compatible with Bitcoin Core (meaning that there are things in Core that are not supported here), but it's getting there and there are just a few minor things missing. So most of the time yes, you can import a descriptor from Core in here, but the other way around is much harder since as you can see there are many things missing from Core that are available here.

> You could just add the export functionality for Bitcoin Core compatible descriptors which you do seem to support.

Yeah I can try to do that, I'll just have to define the right criteria to decide whether a descriptor is supported by Core or not, but it shouldn't be too hard.
