### ISSUE TITLE
signature problems with add_foreign_utxo

### ISSUE THREAD

**Issue by ulrichard** [bitcoindevkit/bdk#334]
I am trying to implement "proof of reserves". For the challenge txin I use add_foreign_utxo.
With the current master branch, it produces a seemingly valid proof psbt. But validating the signatures fails later on.
When I merge https://github.com/afilini/bdk/tree/fix/signer-witness-utxo, then I get the following error when trying to sign: "Missing non_witness_utxo on foreign utxo"

Now I don't know if this is because of a bug in my code or in bdk.

The code is in:
https://github.com/ulrichard/bdk/tree/feature/proof_of_reserves
more specifically in: "src/wallet/reserves.rs"

**Comment by LLFourn** [comment]
So I think that PR (which I am going to review soon) makes non_witness_utxo mandatory. Your code isn't providing a non_witness_utxo: https://github.com/ulrichard/bdk/blob/2d2c4a1e32d2ef411cf784738c945e6145252dab/src/wallet/reserves.rs#L84 so it errors.

I will think about this problem while reviewing that PR later today :)

**Comment by LLFourn** [comment]
To make things work with this PR you just need to do:

```rust
        builder
            .drain_wallet()
            .add_foreign_utxo(challenge_txin.previous_output, challenge_psbt_inp, 42)?
            .fee_absolute(0)
            .only_witness_utxo() // <-- you're missing this.
            .set_single_recipient(out_script_unspendable);
        let (psbt, _details) = builder.finish().unwrap();
```

**Comment by ulrichard** [comment]
Cool, thanks for looking into this. Makes sense.

But after adding only_witness_utxo(), I still get MissingNonWitnessUtxo when running the tests.
I will check again, after the PR is merged.

**Comment by LLFourn** [comment]
To debug you might try and insert a panic inside the places that `MissingNonWitnessUtxo` is called and see why this is occurring. Waiting until that PR is sorted out is also not a bad idea.

**Comment by LLFourn** [comment]
@ulrichard if you use the new API that was merged in https://github.com/bitcoindevkit/bdk/pull/333/files#diff-18f5545e0b6d6f7d1d8ef9f744c9d6d1458baaffc419e69f826626c00dddc260R859 you should be able to do this by passing to `wallet.sign(&mut psbt, SignOptions { trust_witness_utxo: true, ..Default::default() }`. I think this issue can be closed.

**Comment by ulrichard** [comment]
Thanks for the heads up @LLFourn 
Unfortunately, the errors persist.
From what I was able to debug so far, bitcoinconsensus returns SCRIPT_ERR_WITNESS_PROGRAM_WITNESS_EMPTY
On the multisig tests, I am not sure, if my assumptions are wrong, or the number of signatures produced by bdk.

**Comment by afilini** [comment]
Can you check if the transaction is finalized after BDK signs it? It's the second tuple item returned by `sign()`.

<s>Maybe BDK refuses to finalize the entire transaction because there's one input it doesn't recognize, so you only get a PSBT full of partial signatures, which is then turned into a raw transaction with empty scriptSigs and witnesses when extracted.</s>

Nevermind, BDK already correctly finalizes individual inputs. Can you try dumping the PSBT after it gets signed and see if the inputs contain `partial_signatures` (which means they aren't finalized) or `final_script_sig`/`final_script_witness`?

**Comment by ulrichard** [comment]
The boolean "finalized" return value is always false in my tests. So the tx is never actually finalized.

I extended the count_signatures lambda to also count final_script_sig and final_script_witness.
https://github.com/ulrichard/bdk/blob/feature/proof_of_reserves/src/wallet/reserves.rs  line 474
Then I adapted the asserts to reflect the values that are currently produced as opposed to what I would expect.
Unfortunately, I cannot explain those numbers.

**Comment by LLFourn** [comment]
I am not sure I understand this next problem. Can you give us the steps to reproduce?

**Comment by ulrichard** [comment]
Sure:

* git clone https://github.com/ulrichard/bdk
* git checkout --track origin/feature/proof_of_reserves
* vi src/wallet/reserves.rs
* :498
* <change the values in the asserts to what would be reasonable to expect. Specifically, finalized should be true after finalize_psbt(). And the number of the signatures look strange to me at some stages>
* cargo test

What I can't explain:
* why final_script_sig and final_script_witness counts are "num_inp - 1" after the second and third signature, and after finalize_psbt()
* why partial_sigs count is "num_inp * 2 + 1" after the third signature. I would expect "num_inp * 3"
* why partial_sigs stay the same after finalize_psbt(). If I understood correctly, they should disapear when finalizing.

**Comment by afilini** [comment]
> why final_script_sig and final_script_witness counts are "num_inp - 1" after the second and third signature, and after finalize_psbt()

This is probably because BDK only knows how to finalize the multisig inputs, not the "OP_TRUE" proof-of-reserve input. So once there are enough signatures on those inputs, it will finalize them.

> why partial_sigs count is "num_inp * 2 + 1" after the third signature. I would expect "num_inp * 3"

BDK ignores inputs that are already finalized. So in this case the multisig inputs get finalized after the second signature (it's a 2-of-3, so those two are enough) and when you try to sign the third time it will just skip them.

> why partial_sigs stay the same after finalize_psbt(). If I understood correctly, they should disapear when finalizing.

I actually thought it would do that as well, I didn't remember it left the partial_signatures inside. Anyway, that shouldn't cause any troubles, it's just extra data that you don't need anymore left inside the PSBT.

I'll try to experiment with it a little bit, I think a way to fix this might be to pre-finalize the proof-of-reserve input manually, so that BDK will only have to care about the multisig inputs

**Comment by afilini** [comment]
Ok I think I've managed to fix it, there were a couple of things that I had to change:

- Since BDK can't finalize the proof-of-reserve input I just changed line 89 to provide an empty finalized script manually, with `Some(Script::default())`. On the line above I noticed you were doing something similar, setting the `witness_script` to an empty script: you don't actually need that, because the `witness_script` is generally used when making signatures, but in your case nobody needs to sign that input. I guess you were trying to do the right thing here, but unfortunately you picked the wrong field to set

https://github.com/ulrichard/bdk/blob/94d9b5ca37085b848751a712ba6aa264282ae14e/src/wallet/reserves.rs#L89

- At line 133 you were using the `unsigned_tx` which, as the name implies, is always "unsigned". If you want to merge the finalized scripts from the PSBT into a finalized raw transaction you should use `.extract_tx()`. Since `extract_tx` consumes the PSBT, you'll also need to clone it first: `let tx = psbt.clone().extract_tx()`

https://github.com/ulrichard/bdk/blob/94d9b5ca37085b848751a712ba6aa264282ae14e/src/wallet/reserves.rs#L133

- At line 219 you were using the `vout` of your input as the input index. This is wrong, because `bitcoinconsensus` wants to know which input of the transaction it should verify, not which output of the previous transaction is being spent. Just changing that to `i` fixed the issue

https://github.com/ulrichard/bdk/blob/94d9b5ca37085b848751a712ba6aa264282ae14e/src/wallet/reserves.rs#L219

Those three little things should be enough to make it work. One note though: it looks like you are currently trusting the metadata from the PSBT to verify the proof of reserve. This is dangerous and probably wrong: as a verifier you should fetch those data yourself from your node/electrum server/etc (basically from the `Blockchain` instance of your wallet) and verify the proof against them. Otherwise it's trivial for an attacker to craft a PSBT with fake inputs and make it pass the verification successfully.

<details>
  <summary>For completeness, this is the exact diff that I have locally on top of 94d9b5c which passed verification for the case nr 1 of `test_proof_multisig`</summary>

```diff
diff --git a/src/wallet/reserves.rs b/src/wallet/reserves.rs
index 60d0cd8..7c0dcdb 100644
--- a/src/wallet/reserves.rs
+++ b/src/wallet/reserves.rs
@@ -34,7 +34,7 @@
 use bitcoin::{
     blockdata::{
         opcodes,
-        script::Builder,
+        script::{Builder, Script},
         transaction::{OutPoint, TxIn, TxOut},
     },
     consensus::encode::serialize,
@@ -85,8 +85,8 @@ where
                 value: 0,
                 script_pubkey: Builder::new().push_opcode(opcodes::OP_TRUE).into_script(),
             }),
-            witness_script: Some(Builder::new().into_script()),
-            final_script_sig: None,
+            // witness_script: Some(Builder::new().into_script()),
+            final_script_sig: Some(Script::default()), // "finalize" the input with an empty scriptSig
             ..Default::default()
         };
 
@@ -130,7 +130,7 @@ pub fn verify_proof(
     outpoints: Vec<OutPoint>,
     network: Network,
 ) -> Result<u64, Error> {
-    let tx = &psbt.global.unsigned_tx;
+    let tx = psbt.clone().extract_tx();
 
     if tx.output.len() != 1 {
         return Err(Error::ProofOfReservesInvalid(format!(
@@ -216,7 +216,7 @@ pub fn verify_proof(
                     script.to_bytes().as_slice(),
                     value,
                     &serialized_tx,
-                    vout.try_into().unwrap(),
+                    i, // vout.try_into().unwrap(),
                 ),
             )
         })
@@ -427,8 +427,8 @@ mod test {
             MultisigType::Wsh,
             "tb1qnmhmxkaqqz4lrruhew5mk6zqr0ezstn3stj6c3r2my6hgkescm0sg3qc0r"
         ),
-        case(MultisigType::ShWsh, "2NDTiUegP4NwKMnxXm6KdCL1B1WHamhZHC1"),
-        case(MultisigType::P2sh, "2N7yrzYXgQzNQQuHNTjcP3iwpzFVsqe6non")
+        // case(MultisigType::ShWsh, "2NDTiUegP4NwKMnxXm6KdCL1B1WHamhZHC1"),
+        // case(MultisigType::P2sh, "2N7yrzYXgQzNQQuHNTjcP3iwpzFVsqe6non")
     )]
     fn test_proof_multisig(
         script_type: MultisigType,
@@ -491,23 +491,26 @@ mod test {
             ..Default::default()
         };
         let finalized = wallet1.sign(&mut psbt, signopts.clone())?;
-        assert_eq!(count_signatures(&psbt), (num_inp * 1, 0, 0));
+        // assert_eq!(count_signatures(&psbt), (num_inp * 1, 0, 0));
         assert_eq!(finalized, false);
+        println!("SIGN 1: {}", String::from_utf8(encode_tx(&psbt).unwrap()).unwrap());
 
         let finalized = wallet2.sign(&mut psbt, signopts.clone())?;
-        assert_eq!(count_signatures(&psbt), (num_inp * 2, num_inp - 1, num_inp - 1));
-        assert_eq!(finalized, false);
-
-        let finalized = wallet3.sign(&mut psbt, signopts.clone())?;
-        assert_eq!(count_signatures(&psbt), (num_inp * 2 + 1, num_inp - 1, num_inp - 1));
-        assert_eq!(finalized, false);
-
-        let finalized = wallet1.finalize_psbt(&mut psbt, signopts)?;
-        assert_eq!(count_signatures(&psbt), (num_inp * 2 + 1, num_inp - 1, num_inp - 1));
-        if !finalized {
-            write_to_temp_file(&psbt);
-        }
-        assert_eq!(finalized, false);
+        // assert_eq!(count_signatures(&psbt), (num_inp * 2, num_inp - 1, num_inp - 1));
+        // assert_eq!(finalized, false);
+        println!("SIGN 2: {}", String::from_utf8(encode_tx(&psbt).unwrap()).unwrap());
+
+        // let finalized = wallet3.sign(&mut psbt, signopts.clone())?;
+        // // assert_eq!(count_signatures(&psbt), (num_inp * 2 + 1, num_inp - 1, num_inp - 1));
+        // assert_eq!(finalized, false);
+        // println!("SIGN 3: {}", String::from_utf8(encode_tx(&psbt).unwrap()).unwrap());
+
+        // let finalized = wallet1.finalize_psbt(&mut psbt, signopts)?;
+        // assert_eq!(count_signatures(&psbt), (num_inp * 2 + 1, num_inp - 1, num_inp - 1));
+        // if !finalized {
+        //     write_to_temp_file(&psbt);
+        // }
+        // assert_eq!(finalized, false);
 
         let spendable = wallet1.verify_proof(&psbt, &message)?;
         assert_eq!(spendable, balance);
```

</details>

**Comment by ulrichard** [comment]
Thanks a lot for the explanations and the fixes and the suggestions.

@afilini  As to the hint about trusting the metadata of the PSBT:
Currently I fetch the outpoints from electrum 
https://github.com/ulrichard/bdk/blob/94d9b5ca37085b848751a712ba6aa264282ae14e/src/wallet/reserves.rs#L113
and look up each in 
https://github.com/ulrichard/bdk/blob/94d9b5ca37085b848751a712ba6aa264282ae14e/src/wallet/reserves.rs#L156
How would a proof have to be constructed to cheat that?

Ah, and since we are already at this line. Would it be possible with the existing interfaces to check if such a proof would have been valid at a certain blockheight?

**Comment by afilini** [comment]
Sorry, I had completely missed that part where you take the local `list_unspent()`. That's definitely good, but I still think there might be some attack surface on the PSBT metadata, because you are not really checking them.

The main issue I see is when the input provides only a `witness_utxo`: an attacker could add a real outpoint but lie about its value in the `witness_utxo` field. Since that is never checked, that would allow the attacker to "prove" that it has more money than it actually does.

The check on `partial_signatures` is not really necessary and it actually works just because BDK leaves the signatures in there even after it has finalized the PSBT, but the BIP doesn't require it. Maybe it would be better to look at the finalized scriptSig/witness and if both of them are `None` you can consider the input "unsigned". Anyway, even if you skip the step entirely if an input is unsigned it will fail the verification later.

Also, other random things that came to my mind: I think you might also want to check the `SIGHASH` of the signatures in every inputs, with some of them the signature might not cover the challenge input. Maybe it's not a big deal (it's actually probably more dangerous for the attacker itself than the verifier), just something to think about.

Keep in mind that this is not an exhaustive list, there might be something else that I didn't notice. I haven't really spent a lot of time trying to break it, those are just a bunch of things I noticed yesterday while working on it.

> Ah, and since we are already at this line. Would it be possible with the existing interfaces to check if such a proof would have been valid at a certain blockheight?

I don't think so, not with the current API. The database doesn't have "snapshots" or anything, so it's impossible to "go back in time".

**Comment by ulrichard** [comment]
Thanks for all those inputs. 
I implemented some checks and tests for most now.

But I am not sure about the SIGHASH part. Could you elaborate a bit more on that one? I assume you are not talking about sighash_type, as this is None in all of my test cases.

**Comment by afilini** [comment]
Yes, I'm thinking about the SIGHASH type: signatures always have one, and by default `SIGHASH_ALL` is used if a different one isn't specified in the PSBT. The sighash defines which parts of a transaction should be hashed before producing the signature, with the `ALL` variant being the most conservative: it signs pretty much everything, so that adding/removing an input will invalidate the signature.

Generally all the sighashes sign all the inputs (and then either all, none or a single output), but there's an extra flag that can be applied to only sign one input, `ANYONECANPAY`. So what I have in mind is a weird edge case where an attacker can take a signature made with, for instance, `SIGHASH_NONE|ANYONECANPAY` on a different transaction and re-use it as a "proof of reserves".

I don't think there's any way to use this to prove that they have more money than they actually do, but still it's not ideal to accept that as a PoR. BIP 0127 also [mentions this explicitly](https://github.com/bitcoin/bips/blob/master/bip-0127.mediawiki#proof-format):

> The remaining inputs MUST have signatures that commit to the commitment input (e.g. using SIGHASH_ALL).

**Comment by evd0kim** [comment]
Hi. I ran into the same issue on BDK v0.23.0. 

I have some test code which signs PSBT in the single main() and another one which has split signing and psbt creation procedures.

In single main() i have 
```
Error: Rpc(JsonRpc(Rpc(RpcError { code: -26, message: "non-mandatory-script-verify-flag (Witness program was passed an empty witness)", data: None })))
```
on broadcast while PSBT finalizes with success in split test variant. 

In separate test code PSBT gets signed and broadcasted.

Also, the error may change on policy error if I move add_signer procedure before invoking PSBT creation in single main() test.
