### ISSUE TITLE
Better address setup

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/bdk#372]
**Description**

Instead of using the derivation index we should store for each address whether or not it has been "setup" with the blockchain backend. We could merge `Blockchain::setup()` with `Blockchain::sync()` and just let the function decide what to do with each address based on its status.

Probably depends on #359 since we would have to change the db interface.

**Expected Outcomes** 
* Update blockchain module traits and structs as needed and fix corresponding tests
* Add add or combine tests if needed to cover updated functionality 
* Update any modified public traits and structs documentation 

**Resources**  
* [BDK Website](https://bitcoindevkit.org)
* [BDK github repo](https://github.com/bitcoindevkit/bdk)
* [BDK Discord](https://discord.gg/dstn4dQ)

**Skills Required**  
* Experience with git. [Guide](https://git-scm.com/book/en/v2)
* Basic familiarity with rust. [First seven chapters of the book](https://doc.rust-lang.org/book/)
* Familiarity with bitcoin descriptors and address generation
* Familiarity with changes made for schema migration in #359

**Mentor(s)**  
@notmandatory 

**Difficulty**  
Medium

**Competency Test**  
* Install rust, compile and run all bdk examples and tests. 
* Read through the BDK docs.
* Make a dummy wallet with BDK with key-value and sqlite backends. 
* Familiarity with basic rust, should be able to write basic custom trait implementations on foreign structures.

**Comment by notmandatory** [comment]
Per our team chat yesterday I changed this into a summer-of-bitcoin project.

**Comment by LLFourn** [comment]
I think this one needs to be expanded up on since I don't know what I would do with it if I had to tackle it. In particular I'm not totally clear on the motivation and what the result should look like.

**Comment by notmandatory** [comment]
The genesis of this issue is #354. 

My understanding is when addresses are requested (ie. `get_address`) prior to a `sync` and then `setup` isn't called. But by keeping track on individual addresses if they're setup or not at least the first part of #354 is solved since they can be setup if needed every time sync is called. 

In my mind this change will create a table for all `get_address` scripts generated (or at least their indexes) with a boolean indicating if they are "setup" or not. Then when sync is called a query will be done to find any not-setup scripts, and if any are found call setup on them. I think the reason to not setup each script as it's requested is that it would be a performance hit. Also we allow random indexes to be requested so keeping only a range of index not setup wouldn't work.

But maybe there's a better way to address the two issues from #354 and we can explore that with whoever takes this on.

**Comment by notmandatory** [comment]
Closing this issue since sync/scan works differently now with the `bdk_chain` crate in v1.0.0.
