### ISSUE TITLE
InnerXKey is public

### ISSUE THREAD

**Issue by tcharding** [bitcoindevkit/bdk#395]
Code contains the following comment `src/descriptor/mod.rs`
```
// FIXME: `InnerXKey` was made private in rust-miniscript, so we have to implement this manually on
// both `ExtendedPubKey` and `ExtendedPrivKey`.
//
// Revert back to using the trait once https://github.com/rust-bitcoin/rust-miniscript/pull/230 is
// released
```

The linked PR has been merged and was released in 5.1.0 (which we currently depend upon), `InnerXKey` is available but I couldn't work out how to do what the FIXME says.

Opening this issue to flag it, happy to work on it if someone could explain it a little.

Thanks

**Comment by danielabrozzoni** [comment]
It seems to me it just means `XKeyUtils` should be implemented on a `DescriptorXKey<InnerXKey>`, instead of implementing it twice on `DescriptorXKey<ExtendedPubKey>` and `DescriptorXKey<ExtendedPrivKey>` :)

https://github.com/bitcoindevkit/bdk/blob/64e88f0e006c68315142d53dc35b633327dde4b5/src/descriptor/mod.rs#L275:L332

**Comment by tcharding** [comment]
My focus has shifted.

**Comment by notmandatory** [comment]
@tcharding thanks for creating this, I'm reopening since this still sounds like a good thing for someone else to do.
