### ISSUE TITLE
New Sync callback traits

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#488]
**Descriptive Title**  
New `Wallet.sync` callback traits

**Expected Outcomes**  
Add new, optional, `Wallet.sync` callback traits that give the user additional information about changes to the wallet during the sync. For example: 
1. new transactions
2. updated transactions
3. updated wallet balance

**Resources**  
  
  
  
  
  

**Skills Required**  
  
  
  
  

**Mentor(s)**  

**Difficulty**  

**Competency Test (optional)**

**Comment by LLFourn** [comment]
note I think accurately updating the wallet balance is hard given the way "full" sync works with esplora and electrum. This is because you don't know until you're at the end of the sync what the impact of any transaction will be.

Which isn't to say we shouldn't be able to do this -- it is just going to be difficult.

**Comment by notmandatory** [comment]
Good to know, if we are doing callbacks on new and updated transactions that may be enough for now. Then on the other hand adding these new callbacks may not make sense at all since the user can call existing methods after the sync to get all this info from the wallet cache db. 

@artfuldev do you recall when we discussed this for mobile wallets what use cases we had in mind?

**Comment by notmandatory** [comment]
Closing issue since not clear it's needed. Can reopen later once we understand requirements better, but won't use this one for summer-of-bitcoin.
