### ISSUE TITLE
Document that `get_transactions()` might return unsorted txs, show how to sort them if needed

### ISSUE THREAD

**Issue by w0xlt** [bitcoindevkit/bdk#518]
`bdk::wallet::Wallet pub fn list_transactions()` does not return ordered transactions.

I am using the code below to order the transactions. `bdk::types::BlockTime pub timestamp` field can also be used.

```rust
tx_list.sort_by(|a, b| b.confirmation_time.as_ref().unwrap().height.cmp(&a.confirmation_time.as_ref().unwrap().height));
```

**Comment by afilini** [comment]
We discussed this and reached the conclusion that sorting them might end up being a waste of time, since it's not guaranteed that the caller will actually need a sorted vec.

Nonetheless, we think it could be useful to document the fact that they might not be sorted (it really depends on the `Database` used) and provide an example in case somebody actually needs them sorted.

I'll change the title of the issue accordingly.

**Comment by gabbyprecious** [comment]
Hello @afilini, can I work on this?

**Comment by notmandatory** [comment]
Hi @gabbyprecious, yes it's all yours, I'll put your name on it. If you have any questions feel free to comment here or on the Bitcoin Dev Kit discord.

**Comment by evanlinjin** [comment]
Hi all, is there progress on this? If not, I can take this on if needed.

**Comment by notmandatory** [comment]
@gabbyprecious please let us know if you're still working on this one. If not I'll reassign it.

**Comment by danielabrozzoni** [comment]
Unassigning... @evanlinjin let me know if you want to work on this yourself 😁

**Comment by evanlinjin** [comment]
> Unassigning... @evanlinjin let me know if you want to work on this yourself 😁 

Thank you for the thought! However I have my hands full now as you know 😅

**Comment by w0xlt** [comment]
Done in https://github.com/bitcoindevkit/bdk/pull/686
