### ISSUE TITLE
Make `EsploraBlockchain` accessable to outside libraries

### ISSUE THREAD

**Issue by benthecarman** [bitcoindevkit/bdk#568]
I am working on a project and need to make requests to a esplora backend. Would be nice if I could use bdk's implementation.

**Comment by LLFourn** [comment]
Hey @benthecarman. It'd be useful to know what bits of esplora you'd like to use from BDK. We're currently thinking about a `v1.0` release and a big part of that might be **removing** all API surface area for esplora except for the bit that keeps the wallet up to date.

Having said that I think it makes sense to expose at least a user agent that can make requests to a specific path in the api (you'd have to deserilaize the responses into types yourself though).

But perhaps since we've already implemented it we could keep and expose the esplora API (even the bits we don't use) and just rely on people who use those parts to make PRs and keep it up to date.

**Comment by benthecarman** [comment]
It'd be nice to have full api coverage. It probably makes sense to make it a separate library that bdk relies on

**Comment by LLFourn** [comment]
Sure thanks. Yep the plan is to make it separate.

**Comment by afilini** [comment]
We've recently moved our esplora client into this separate crate: https://github.com/bitcoindevkit/rust-esplora-client

The goal now is to integrate it into BDK for the next release

**Comment by notmandatory** [comment]
Closing now that `rust-esplora-client` is published and #764 is merged.

https://crates.io/crates/esplora-client
