### ISSUE TITLE
SqliteDatabase set_utxo always inserts new utxo

### ISSUE THREAD

**Issue by johncantrell97** [bitcoindevkit/bdk#591]
**Describe the bug**  
When `set_utxo` is called the intention is to `insert_or_update` based on the outpoint.  The current implementation always inserts a new utxo and there is no unique constraint on the table.

**To Reproduce**  
Call `set_utxo` with the same &LocalUtxo twice.

**Expected behavior**  
When set_utxo is called twice with the same LocalUtxo there should only be a single utxo in the database.

**Additional context**  
This probably should use a unique index but it was created as just a regular index.  I assume we'll need to add new migration to handle it.  The problem is that adding the unique constraint can fail because people might already have databases with multiple utxos with the same outpoint. 

We would need to be able to run a data migration to remove the duplicates which is complicated for two reasons.  First, there's no concept of a data migration at the moment but I guess they are currently just sql statements.  Second, there's no way to know which one's to keep or delete, right? I guess is there ever a case where it would be "updating" a utxo? Is that even possible?

**Comment by rajarshimaitra** [comment]
One thing that came to mind is can we programmatically do it in the database itself?? Like in `set_utxo` definition we can say check if the utxo already exists, or else add it there. And then we can have a sanity run somewhere in default sync to sanitize the utxo set at wallet setup?? In that way people using previous version and having duplicate utxos can get their db clean when they switch to the new version and execute the first `wallet_setup`.. And it would only be a one time sanity cost, as subsequent duplication tests will be small..  

Maybe later we can set the sqlite db as unique index too, but we can't do that for other dbs right?? They have to be manually checked.. So maybe makes sense to add the sanity logic somewhere in `database` module itself, probably within `set_utxo`.. 

One thing that @LLFourn mentioned in last call that he intends to take the utxo set and other DB data into memory at run time and and then do periodic flushing to the database. In that scenario if we say the utxo set is a `HashSet` instead of a `Vec` then uniqueness can be guaranteed in run time too without the sanity logic. 

But till that happens I think sanity check is the only way for now..

**Comment by notmandatory** [comment]
I don't see any reason why duplicate UTXOs would have different values if they have the same txid + vout so in #605 I remove duplicates and add a new unique constrain based on txid + vout. Worst case it could be possible that one entry says the coin is spent and another says it's not, and we keep the one that says it's not spent, then the normal wallet sync should make the required update.
