### ISSUE TITLE
Light client library to monitor mempool

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#61]
Suggestion from @moneyball. Create a library that allows a light client to use the p2p network to monitor the mempool. today, the only way you can do this is with Core, which implies running a fully validating node. however, there is no reason you need to do IBD or validation in order to just monitor the mempool. why would a light client want to monitor the mempool?
1. self sovereign improved fee estimation
1. self sovereign watchtower (for LN or various other L2/custody protocols that have been proposed which require monitoring for certain txn and responding)
1. perhaps certain analytical tools (would be awesome if devs could focus on the analytical tool and utilize BDK to deal with all the details vs. write from scratch)

**Comment by afilini** [comment]
Fee estimation is actually pretty hard if you only look at the mempool, because you don't know the value of the inputs that are being spent. You might be able to estimate it by downloading the latest `x` blocks and only considering txs spending outputs from these blocks (or the mempool itself), but it might not be optimal.

**Comment by moneyball** [comment]
Ah interesting. The UTXO set is needed I assume?

I am curious how utreexo would handle this then?

**Comment by LLFourn** [comment]
> Fee estimation is actually pretty hard if you only look at the mempool, because you don't know the value of the inputs that are being spent. 

Also you have no idea whether the stuff in your mempool is actually valid at all. How would you filter out invalid transaction spam?

> Ah interesting. The UTXO set is needed I assume?

I think so.

> I am curious how utreexo would handle this then?

It's a good question. I don't know if the vision for utreexo nodes is to have a mempool at all. You could do it you just have to have inclusion proofs for each output being spent being broadcast by the "bridge node" as the enter the mempool.

**Comment by afilini** [comment]
Well, the fact that they could be invalid is pretty much unavoidable with light clients. Even when you download blocks you are just checking the PoW, but the transactions they contain could be invalid in any sort of ways.

For some use cases that isn't a problem though, if you are a watchtower for instance. You don't care about transactions being valid, you are just looking for some specific txids.

For fee estimation specifically, I think what most light clients do is rely on centralized (trusted) services. I'm pretty sure LND does it when using neutrino and I was planning to add this here to BDK too, since currently the fee estimation in the `CompactFilters` blockchain is a TODO. I'm not sure about utreexo, I've never looked too much into it.

**Comment by notmandatory** [comment]
Closing this for now since there doesn't seem to be a good way to monitor the mempool in light clients. A better approach for fee estimation based on prior blocks is described in the blog post series ["Fee estimation for light-clients"](https://bitcoindevkit.org/blog/2021/01/fee-estimation-for-light-clients-part-1/).
