### ISSUE TITLE
BDK rejects any SSL server that uses a self-signed certificate

### ISSUE THREAD

**Issue by BitcoinQnA** [bitcoindevkit/bdk#627]
**Describe the bug**  
BDK rejects any SSL server that uses a self-signed certificate. This issue is being observed in [Envoy](https://foundationdevices.com/envoy/), our pre-release companion application for our [Passport](https://foundationdevices.com/passport/) hardware wallet. 

![photo_2022-06-07_09-57-43](https://user-images.githubusercontent.com/64638670/172340349-e6ed108f-f000-4c4b-a7f1-984e2782dd8d.jpg)

**Connecting to our default server (also Fulcrum) with a certificate issued by Let's Encrypt works fine.** 

<br/>

**To Reproduce**  
Attempt to connect to any Electrum Server that uses a self-signed certificate. We have been using `ssl://testnet.aranguren.org:51002`, a public Fulcrum server used (successfully) by Sparrow Wallet when started in testnet mode. 

**Expected behavior**  
Successful connection.

**Build environment**  
 - BDK tag/commit: a328607d27feb5d556df99ec6beabc41cc655160
 - OS+version: Android 12
 - Rust/Cargo version: 1.54.0
 - Rust/Cargo target: aarch64-linux-android

**Additional context**  
N/A

**Comment by afilini** [comment]
If you want to use self signed certs you have to explicitly enable it by creating the electrum client manually with a custom configuration and setting [`Config::validate_domain()`](https://docs.rs/electrum-client/latest/electrum_client/struct.Config.html#method.validate_domain) to `false`.

On top of that, I think the `BadDER` is some kind of encoding error, I don't think it's failing because it's self signed. Other people have had the same issue with it in the past, see https://github.com/Blockstream/gdk/pull/141

Sometimes rustls is picky about those stuff, try overriding rust-electrum-client to use openssl with the `use-openssl` feature. Keep in mind that openssl is written in C, so you'll need the NDK setup to cross-compile for android.

**Comment by BitcoinQnA** [comment]
Thank you for the feedback.
