### ISSUE TITLE
Electrum vs Electrumx vs Fulcrum

### ISSUE THREAD

**Issue by nourou4them** [bitcoindevkit/bdk#632]
I am a liitle bit confused on the requirements for using the bdk.
While reading the [documentation ](https://bitcoindevkit.org/bdk-cli/interface/#options-2)n I can see we have to setup a server, this one being the default one : ssl://electrum.blockstream.info.

Should I install Electrum server, ElectrumX or Esplora by Blockstream ?

Also, I have a Fulcrum server already running on my node, could I connect it to the bdk ?

**Comment by afilini** [comment]
All of them should be working fine, the protocol is the same. The underlying library [rust-electrum-client](github.com/bitcoindevkit/rust-electrum-client) is tested against electrs (the vanilla version, not blockstream's fork) and electrumx and it works fine. I'm guessing it should work with fulcrum as well.

If you find any issues with fulcrum please report them on that repo, most of the electrum code is sitting there and if something breaks it's most likely because of an issue in there.

**Comment by nourou4them** [comment]
Ok got it.
Thanks for the answer.
