### ISSUE TITLE
Compilation fails when both "rpc" and "async-interface" feature is on.

### ISSUE THREAD

**Issue by joemphilips** [bitcoindevkit/bdk#781]
**Describe the bug**  

When I tried to use bdk with two features "rpc" and "async-interface"  in my own project it failed to compile.
Is this intended behavior? I could not find any documentation.

**To Reproduce**  

```sh
git clone https://github.com/bitcoindevkit/bdk
cd bdk
git checkout master # or `git checkout v0.23.0`
cargo build --features=async-interface,rpc --no-default-features
```

**Expected behavior**  

`cargo build` returns exit code 0

Compilati

**Build environment**  
 - BDK tag/commit: master or v0.23.0
 - OS+version: ubuntu 18.04.6
 - Rust/Cargo version: cargo 1.64.0 (387270bc7 2022-09-16), rustc 1.64.0 (a55dd71d5 2022-09-19)
 - Rust/Cargo target: stable-x86_64-unknown-linux-gnu

**Comment by notmandatory** [comment]
Sorry this isn't well documented, but you can not use the `async-interface` feature with the `rpc` feature, `async-interface` is only supported with `use-esplora-async`. The only place this is currently documented is below. But due to the work going on with [`bdk_core`](https://bitcoindevkit.org/blog/bdk-core-pt1/), much of this will be changing so there's no point in fixing it now. 

https://github.com/bitcoindevkit/bdk/blob/ea47d7a35bf3c3a1592b473ae93102e52ddf47f4/Cargo.toml#L69

This command will work if you want to use the `async-interface` feature now:
```
cargo build --features=async-interface,use-esplora-async --no-default-features
```

**Comment by joemphilips** [comment]
I see, thanks for the feedback.
