### ISSUE TITLE
Bitcoin core RPC client

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#79]
https://github.com/rust-bitcoin/rust-bitcoincore-rpc

**Comment by justinmoon** [comment]
I have an out-of-date prototype of this at https://github.com/bitcoindevkit/bdk/pull/22

I want to integrate magical with a bitcoind instance running locally. RPC is a little awkward because the node becomes stateful. You need to tell the Bitcoin Core wallet to track addresses, create and load watch-only wallets.

Other options for this usecase would be compact block filters over p2p or RPC. In the extreme, bdk could parse raw blocks in `~/.bitcoin/blocks` like electrum servers do.

**Comment by afilini** [comment]
Also relevant: #86
