### ISSUE TITLE
Substitute `enable_rbf` in `TxBuilder` with `disable_rbf`

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bdk#791]
i.e., maybe all our txs should be RBF by default :)

**Comment by notmandatory** [comment]
Concept ACK, seems to be direction bitcoin core is going with bitcoin/bitcoin#25353. Even with all the controversy I think best practice from a general wallet point of view is to enable RBF so fees can easily be bumped when needed.

**Comment by notmandatory** [comment]
Since this is a breaking change we're going to hold off on this until 1.0 since that is a more obviously breaking release.

**Comment by notmandatory** [comment]
A small change but I think we should push to 2.0 milestone.

**Comment by FlamingSaint** [comment]
@notmandatory I would like to work on this, As far as I have understood I need to replace **enable_rbf** with **disable_rbf** in **tx_builder.rs**. This new function shouldn't initialize the value of _rbf_ with some default value. Also, I assume I need to replace all instances of **enable_rbf** with **disable_rbf**.

**Comment by notmandatory** [comment]
@FlamingSaint hi sure go ahead and create a PR, there might also be some additional related changes, see discord discussion here: https://discord.com/channels/753336465005608961/753367451319926827/1228063458952478792

**Comment by notmandatory** [comment]
@FlamingSaint  per your question on discord, yes you should use the same PR to make RBF the default for TxBuilder. So yes add `disable_rbf()` but since we still need a way to re-enable and enable RBF with a sequence, how about keeping the existing `enable_rbf()` and `enable_rbf_with_sequence(RbfValue)`?  

Btw, let's keep the discussion here for people who don't use discord.

**Comment by luisschwab** [comment]
I'm picking up this issue, as it seems to have gone stale.
