### ISSUE TITLE
Coin control & UTXO blacklisting

### ISSUE THREAD

**Issue by willcl-ark** [bitcoindevkit/bdk#98]
Two related privacy features I'd like to see implemented in the future:

1) per-UTXO coin control during transaction construction
1) blacklisting of individual UTXO(s) to combat dusting attacks

**Comment by afilini** [comment]
We already kinda support coin blacklisting, whenever a transaction is created the user can specify [a list of utxos which must not be spent](https://bitcoindevkit.org/docs-rs/bdk/0.1.0-beta.1/bdk/wallet/tx_builder/struct.TxBuilder.html#method.unspendable).

I'm not sure what you mean with "per-UTXO coin control", but users of the library can also implement their own [`CoinSelectionAlgorithm`](https://bitcoindevkit.org/docs-rs/bdk/0.1.0-beta.1/bdk/wallet/coin_selection/trait.CoinSelectionAlgorithm.html) which can have arbitrary logic, and that is also selected using the [`TxBuilder`](https://bitcoindevkit.org/docs-rs/bdk/0.1.0-beta.1/bdk/wallet/tx_builder/struct.TxBuilder.html), so the logic is not fixed for the whole wallet, but it can be changed for each transaction.

The reason why we don't store internally whether a coin is spendable or not is because of mainly two reasons:

1. It would introduce some data in the database which cannot be recreated just by looking at the blockchain. This is why I sometimes refer to the database as a "cache", because if you lose it, you won't lose your funds or any important metadata (i.e. unspendable flag, labels, etc) with it.

2. Assigning those metadata to a utxo is pretty trivial. It seems way overkill to me to write that part in rust and then having to maintain the bindings for something that can probably be done in a much better way natively on each platform that supports the library. Also, I expect many developers will want to add even more metadata to a utxo (mainly labels, probably more) so I guess they would end up writing their own external map anyways, ignoring ours.

So we definitely want to let the users have full control over the way a transaction is constructed, but we don't want to store anything more than what the wallet needs to operate. There are better solutions for storing metadata on each platform, like [shared storage](https://developer.android.com/training/data-storage/shared-preferences) on Android, [local storage](https://developer.mozilla.org/it/docs/Web/API/Window/localStorage) in the browser, etc. Users also have to store the full descriptor (which may contain private keys) by themselves for the same reason.

**Comment by willcl-ark** [comment]
Thanks Alekos, I agree that passing in a "filter" of unspendable transactions from the application makes much more sense for a library such as this.

I think as Coin Control is such a requested wallet feature, I might try and create a simple example which demonstrates how a developer could implement it using the `Unspendable` list, so that they don't miss it like I did!
