### ISSUE TITLE
Wallet::get_address should return an Result

### ISSUE THREAD

**Issue by LLFourn** [bitcoindevkit/bdk#996]
Since the persistent backend is fallible. There are `expect("TODO")` in there now which seem to have slipped through the cracks. It would be good to differentiate between those calls that are fallible and those that are infallible.
I think `AddressIndex` should go in favor of different methods that return different addresses since the error cases seem to be different.

I think with an infallible persistence backend we can have `new_address` but if it's fallible then it should be `try_new_address` and return a `Result`.

cc @notmandatory. IIRC you were thinking about how to redesign this.

**Comment by nondiremanuel** [comment]
Is this part of 1.0 version or should I assign it to maintenance?

**Comment by LLFourn** [comment]
Thanks i put 1.0.0 on now.

**Comment by nondiremanuel** [comment]
@LLFourn FYI I removed the 1.0.0 milestone both from this and from the bitcoindevkit/bdk_wallet#148 issue since we are using the Project "BDK 1.0" for issues / PRs related in general to 1.0 version. We use the milestones (alpha.1, alpha.2 ...) to signal the "sub-version" in which the specific ticket will eventually be delivered in

**Comment by LLFourn** [comment]
This should be fixed before  `1.0.0-alpha.1`.  at least the `expect("TODO")` bits. A redesign can come in a further release so we just need a small quick fix for now.

**Comment by notmandatory** [comment]
Removed from alpha.1, can see if able to get enough review for alpha.2.
